In [1]:
# Import Desired Library:
import pandas as pd
import numpy as np

In [3]:
# uploading the Dataset.
train=pd.read_parquet("train.parquet")
test=pd.read_parquet("test.parquet")

In [50]:
#Viewing the dataset.
train.head(30)

                             Patient-Uid       Date           Incident
0   a0db1e73-1c7c-11ec-ae39-16262ee38c7f 2019-03-09  PRIMARY_DIAGNOSIS
1   a0dc93f2-1c7c-11ec-9cd2-16262ee38c7f 2015-05-16  PRIMARY_DIAGNOSIS
3   a0dc94c6-1c7c-11ec-a3a0-16262ee38c7f 2018-01-30     SYMPTOM_TYPE_0
4   a0dc950b-1c7c-11ec-b6ec-16262ee38c7f 2015-04-22        DRUG_TYPE_0
8   a0dc9543-1c7c-11ec-bb63-16262ee38c7f 2016-06-18        DRUG_TYPE_1
9   a0dc9577-1c7c-11ec-8b4d-16262ee38c7f 2019-12-16        DRUG_TYPE_1
11  a0dc95c6-1c7c-11ec-8e77-16262ee38c7f 2020-02-07        DRUG_TYPE_1
12  a0dc95f9-1c7c-11ec-b968-16262ee38c7f 2019-08-01        DRUG_TYPE_1
14  a0dc962a-1c7c-11ec-8a51-16262ee38c7f 2017-06-20        DRUG_TYPE_1
16  a0dc9659-1c7c-11ec-a91e-16262ee38c7f 2015-11-25        DRUG_TYPE_2
17  a0dc9689-1c7c-11ec-9ca7-16262ee38c7f 2016-08-07        TEST_TYPE_0
19  a0dc96ca-1c7c-11ec-89e9-16262ee38c7f 2016-09-14        DRUG_TYPE_2
20  a0dc96fb-1c7c-11ec-82ed-16262ee38c7f 2018-11-02        DRUG_TYPE_3
21  a0dc972c-1c7c-11ec-a850-16262ee38c7f 2015-07-04        DRUG_TYPE_1
24  a0dc975b-1c7c-11ec-bb4a-16262ee38c7f 2019-04-03        DRUG_TYPE_2
25  a0dc978b-1c7c-11ec-9956-16262ee38c7f 2018-03-01        DRUG_TYPE_3
26  a0dc97bd-1c7c-11ec-a9d4-16262ee38c7f 2015-08-02  PRIMARY_DIAGNOSIS
27  a0dc97ee-1c7c-11ec-b241-16262ee38c7f 2016-01-27        DRUG_TYPE_4
28  a0dc981e-1c7c-11ec-b4aa-16262ee38c7f 2017-09-21        DRUG_TYPE_5
30  a0dc984d-1c7c-11ec-b4de-16262ee38c7f 2018-01-13     SYMPTOM_TYPE_0
31  a0dc987c-1c7c-11ec-b249-16262ee38c7f 2015-05-06        DRUG_TYPE_0
34  a0dc98ae-1c7c-11ec-82ad-16262ee38c7f 2018-10-05        DRUG_TYPE_6
36  a0dc98e7-1c7c-11ec-9cc8-16262ee38c7f 2019-11-29        DRUG_TYPE_8
38  a0dc9919-1c7c-11ec-8049-16262ee38c7f 2016-07-06        DRUG_TYPE_6
41  a0dc9950-1c7c-11ec-818a-16262ee38c7f 2017-04-05        DRUG_TYPE_7
44  a0dc9982-1c7c-11ec-be1a-16262ee38c7f 2015-07-28        DRUG_TYPE_1
46  a0dc99b3-1c7c-11ec-856e-16262ee38c7f 2018-01-28        DRUG_TYPE_5
48  a0dc99e2-1c7c-11ec-a822-16262ee38c7f 2019-12-12        DRUG_TYPE_0
49  a0dc9a12-1c7c-11ec-a92d-16262ee38c7f 2019-01-03        DRUG_TYPE_0
51  a0dc9a42-1c7c-11ec-842c-16262ee38c7f 2016-07-02     SYMPTOM_TYPE_1

In [5]:
# dROPPING THE DATE AS IT DOESNOT HAVE SIGNIFICANT ROLE.
train1=train.drop('Date',axis=1)

In [6]:
train1.head(2)

                            Patient-Uid           Incident
0  a0db1e73-1c7c-11ec-ae39-16262ee38c7f  PRIMARY_DIAGNOSIS
1  a0dc93f2-1c7c-11ec-9cd2-16262ee38c7f  PRIMARY_DIAGNOSIS

In [7]:
# Doing OneHotEncoding:
train_data=pd.get_dummies(train['Incident'], drop_first=True)

In [9]:
# Concating the datasets.
train2=pd.concat([train1,train_data],axis=1)

In [10]:
# Dropping the Incident feature as it now Encoded.
train3=train2.drop('Incident',axis=1)

In [11]:
train3.head(2)

,Patient-Uid,DRUG_TYPE_1,DRUG_TYPE_10,DRUG_TYPE_11,DRUG_TYPE_12,DRUG_TYPE_13,DRUG_TYPE_14,DRUG_TYPE_15,DRUG_TYPE_16,DRUG_TYPE_17,...,SYMPTOM_TYPE_7,SYMPTOM_TYPE_8,SYMPTOM_TYPE_9,TARGET DRUG,TEST_TYPE_0,TEST_TYPE_1,TEST_TYPE_2,TEST_TYPE_3,TEST_TYPE_4,TEST_TYPE_5
0,a0db1e73-1c7c-11ec-ae39-16262ee38c7f,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,a0dc93f2-1c7c-11ec-9cd2-16262ee38c7f,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [12]:
# Values of Traget Variable.
train3['TARGET DRUG'].value_counts()

0    3153650
1      67218
Name: TARGET DRUG, dtype: int64

In [13]:
# Extracting the target 0 values
train0=train3[train3['TARGET DRUG']==0]

In [14]:
# Extracting the target 1 values
train01=train3[train3['TARGET DRUG']==1]

In [15]:
# sampling the dataset.
train00=train0.sample(n=67218)

In [16]:
# Grouping the dataset of target 0 by patient uid
train00_data=train00.groupby(by='Patient-Uid',as_index=False).mean()

In [17]:
train00_data.head(2)

,Patient-Uid,DRUG_TYPE_1,DRUG_TYPE_10,DRUG_TYPE_11,DRUG_TYPE_12,DRUG_TYPE_13,DRUG_TYPE_14,DRUG_TYPE_15,DRUG_TYPE_16,DRUG_TYPE_17,...,SYMPTOM_TYPE_7,SYMPTOM_TYPE_8,SYMPTOM_TYPE_9,TARGET DRUG,TEST_TYPE_0,TEST_TYPE_1,TEST_TYPE_2,TEST_TYPE_3,TEST_TYPE_4,TEST_TYPE_5
0,a0dc93f2-1c7c-11ec-9cd2-16262ee38c7f,0.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
1,a0dc94c6-1c7c-11ec-a3a0-16262ee38c7f,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.333333,0.0,0.0,0.0,0.0,0.0

In [18]:
# changeing the datatype of target value.
train00_data['TARGET DRUG']=train00_data['TARGET DRUG'].astype(int)

In [19]:
train00_data.head(2)

,Patient-Uid,DRUG_TYPE_1,DRUG_TYPE_10,DRUG_TYPE_11,DRUG_TYPE_12,DRUG_TYPE_13,DRUG_TYPE_14,DRUG_TYPE_15,DRUG_TYPE_16,DRUG_TYPE_17,...,SYMPTOM_TYPE_7,SYMPTOM_TYPE_8,SYMPTOM_TYPE_9,TARGET DRUG,TEST_TYPE_0,TEST_TYPE_1,TEST_TYPE_2,TEST_TYPE_3,TEST_TYPE_4,TEST_TYPE_5
0,a0dc93f2-1c7c-11ec-9cd2-16262ee38c7f,0.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0,0.000000,0.0,0.0,0.0,0.0,0.0
1,a0dc94c6-1c7c-11ec-a3a0-16262ee38c7f,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0,0.333333,0.0,0.0,0.0,0.0,0.0

In [20]:
# Grouping the dataset of target 1 by patient uid
train01_data=train01.groupby(by='Patient-Uid',as_index=False).mean()

In [21]:
train01_data.head(2)

,Patient-Uid,DRUG_TYPE_1,DRUG_TYPE_10,DRUG_TYPE_11,DRUG_TYPE_12,DRUG_TYPE_13,DRUG_TYPE_14,DRUG_TYPE_15,DRUG_TYPE_16,DRUG_TYPE_17,...,SYMPTOM_TYPE_7,SYMPTOM_TYPE_8,SYMPTOM_TYPE_9,TARGET DRUG,TEST_TYPE_0,TEST_TYPE_1,TEST_TYPE_2,TEST_TYPE_3,TEST_TYPE_4,TEST_TYPE_5
0,a0e9c384-1c7c-11ec-81a0-16262ee38c7f,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
1,a0e9c3b3-1c7c-11ec-ae8e-16262ee38c7f,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0

In [22]:
train01_data1=train01_data.drop('Patient-Uid',axis=1)

In [23]:
train01_data01=train01_data1.apply(lambda x:x.astype(float))

In [24]:
train01_data11=pd.concat([pd.DataFrame(train01_data['Patient-Uid']),train01_data01],axis=1)

In [25]:
# Concating the data to form new dataset for taining purspose.
Train_data=pd.concat([train00_data,train01_data11],axis=0)

In [26]:
# splitting the dataset to independent and dependent variable
x_train=Train_data.drop(['TARGET DRUG','DRUG_TYPE_18'],axis=1)

In [27]:
x_train1=x_train.drop('Patient-Uid',axis=1)

In [28]:
# splitting the dataset to independent and dependent variable
y_train=Train_data['TARGET DRUG']

In [51]:
test.head(30)

                             Patient-Uid       Date           Incident
0   a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2016-12-08     SYMPTOM_TYPE_0
1   a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2018-10-17        DRUG_TYPE_0
2   a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2017-12-01        DRUG_TYPE_2
3   a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2018-12-05        DRUG_TYPE_1
4   a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2017-11-04     SYMPTOM_TYPE_0
6   a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2018-05-09  PRIMARY_DIAGNOSIS
7   a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2018-07-07        DRUG_TYPE_8
8   a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2016-12-08        TEST_TYPE_0
9   a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2019-05-21        DRUG_TYPE_0
10  a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2016-06-23        DRUG_TYPE_7
11  a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2017-12-22        DRUG_TYPE_8
12  a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2016-12-08        DRUG_TYPE_0
13  a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2018-10-17        DRUG_TYPE_8
14  a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2017-09-12  PRIMARY_DIAGNOSIS
15  a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2018-05-09        DRUG_TYPE_0
16  a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2017-12-21        DRUG_TYPE_8
17  a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2018-10-01        DRUG_TYPE_8
18  a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2017-12-21  PRIMARY_DIAGNOSIS
19  a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2018-06-07        DRUG_TYPE_8
20  a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2017-12-01  PRIMARY_DIAGNOSIS
21  a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2016-12-08  PRIMARY_DIAGNOSIS
22  a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2018-05-09        DRUG_TYPE_8
23  a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2018-12-05        DRUG_TYPE_0
24  a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2018-09-27        DRUG_TYPE_8
25  a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2017-09-12  PRIMARY_DIAGNOSIS
26  a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2017-12-01  PRIMARY_DIAGNOSIS
27  a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2018-05-09  PRIMARY_DIAGNOSIS
28  a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2019-01-02        DRUG_TYPE_1
29  a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2018-09-27  PRIMARY_DIAGNOSIS
30  a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2016-12-08       DRUG_TYPE_11

In [30]:
test1=test.drop('Date',axis=1)

In [31]:
test1.head(2)

                            Patient-Uid        Incident
0  a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f  SYMPTOM_TYPE_0
1  a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f     DRUG_TYPE_0

In [32]:
# Doing OneHotEncoding:
test_data=pd.get_dummies(test['Incident'],drop_first=True)

In [33]:
# Concating the datasets.
test2=pd.concat([test1,test_data],axis=1)

In [34]:
# Dropping the Incident feature as it now Encoded.
test3=test2.drop('Incident',axis=1)

In [35]:
test3.head(2)

,Patient-Uid,DRUG_TYPE_1,DRUG_TYPE_10,DRUG_TYPE_11,DRUG_TYPE_12,DRUG_TYPE_13,DRUG_TYPE_14,DRUG_TYPE_15,DRUG_TYPE_16,DRUG_TYPE_17,...,SYMPTOM_TYPE_6,SYMPTOM_TYPE_7,SYMPTOM_TYPE_8,SYMPTOM_TYPE_9,TEST_TYPE_0,TEST_TYPE_1,TEST_TYPE_2,TEST_TYPE_3,TEST_TYPE_4,TEST_TYPE_5
0,a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [36]:
test3.shape

(1065524, 55)

In [37]:
# Grouping the dataset of test by patient uid.
Test_data=test3.groupby('Patient-Uid',as_index=False).mean()

In [38]:
# Viewing the Dataset.
Test_data.sample(4)

,Patient-Uid,DRUG_TYPE_1,DRUG_TYPE_10,DRUG_TYPE_11,DRUG_TYPE_12,DRUG_TYPE_13,DRUG_TYPE_14,DRUG_TYPE_15,DRUG_TYPE_16,DRUG_TYPE_17,...,SYMPTOM_TYPE_6,SYMPTOM_TYPE_7,SYMPTOM_TYPE_8,SYMPTOM_TYPE_9,TEST_TYPE_0,TEST_TYPE_1,TEST_TYPE_2,TEST_TYPE_3,TEST_TYPE_4,TEST_TYPE_5
4530,a0fd4878-1c7c-11ec-8e0e-16262ee38c7f,0.353659,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.012195,0.0000,0.000000,0.0,0.00,0.000000,0.000000,0.0,0.0,0.0
3046,a0fc2fcc-1c7c-11ec-ac4c-16262ee38c7f,0.305085,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0000,0.000000,0.0,0.00,0.016949,0.016949,0.0,0.0,0.0
60,a0f9f5b4-1c7c-11ec-866f-16262ee38c7f,0.434211,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.039474,0.0000,0.013158,0.0,0.00,0.026316,0.000000,0.0,0.0,0.0
325,a0fa2800-1c7c-11ec-9c32-16262ee38c7f,0.050000,0.0,0.0125,0.0,0.0,0.0,0.0,0.0,0.0,...,0.012500,0.0375,0.000000,0.0,0.05,0.100000,0.000000,0.0,0.0,0.0

In [39]:
Test_data.shape

(11482, 55)

In [40]:
x_Test_data=Test_data.drop('Patient-Uid',axis=1)

In [41]:
x_Test_data.shape

(11482, 54)

In [42]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [43]:
lr=LogisticRegression()
model_train=lr.fit(x_train1,y_train)

In [44]:
predict_train=lr.predict(x_train1)
score=accuracy_score(predict_train,y_train)
score

0.9742410303587856

In [45]:
predict_test=lr.predict(x_Test_data).astype(int)

In [47]:
data=pd.DataFrame(predict_test)
data1=pd.concat([pd.DataFrame(Test_data['Patient-Uid']),data],axis=1)

In [48]:
data1.to_excel("Sample_submission.xlsx")